INSERT INTO reference (type, name, created_at) VALUES
  ('book', 'GSW18', current_timestamp),
  ('book', 'KS2018', current_timestamp),
  ('book', 'DSST2018', current_timestamp),
  ('book', 'CDPS2018', current_timestamp),
  ('book', 'DGST2017', current_timestamp),
  ('book', 'LHMSA17', current_timestamp),
  ('book', 'DEHS17', current_timestamp),
  ('book', 'SS17b', current_timestamp),
  ('book', 'LSS17', current_timestamp),
  ('book', 'KS16', current_timestamp),
  ('book', 'OS14', current_timestamp),
  ('book', 'DLSZ12', current_timestamp),
  ('book', 'PST11', current_timestamp),
  ('book', 'BPRSS10a', current_timestamp),
  ('book', 'BLSZ18', current_timestamp),
  ('book', 'CIRS18', current_timestamp),
  ('book', 'KOS18', current_timestamp),
  ('book', 'CDSS18', current_timestamp),
  ('book', 'ST18', current_timestamp),
  ('book', 'BHS18', current_timestamp),
  ('book', 'LSW17b', current_timestamp),
  ('book', 'LSW17a', current_timestamp),
  ('book', 'SLST17', current_timestamp),
  ('book', 'SS117a', current_timestamp),
  ('book', 'ILLS17', current_timestamp),
  ('book', 'APSS17', current_timestamp),
  ('book', 'SS17', current_timestamp),
  ('book', 'BGLFS17', current_timestamp),
  ('book', 'SST17', current_timestamp),
  ('book', 'LS17', current_timestamp),
  ('book', 'ILS16', current_timestamp),
  ('book', 'DS16a', current_timestamp),
  ('book', 'DIS16', current_timestamp),
  ('book', 'DS16', current_timestamp),
  ('book', 'CGSSZ16', current_timestamp),
  ('book', 'LSSS16', current_timestamp),
  ('book', 'OPPS16', current_timestamp),
  ('book', 'PSSW16', current_timestamp),
  ('book', 'SS15', current_timestamp),
  ('book', 'PSSW15', current_timestamp),
  ('book', 'BJMS15', current_timestamp),
  ('book', 'DEPS15', current_timestamp),
  ('book', 'ILS14', current_timestamp),
  ('book', 'ABPS14,', current_timestamp),
  ('book', 'KLS14', current_timestamp),
  ('book', 'HSV14', current_timestamp),
  ('book', 'PST14', current_timestamp),
  ('book', 'HLS14', current_timestamp),
  ('book', 'ASZ14', current_timestamp),
  ('book', 'LSS14', current_timestamp),
  ('book', 'BLSZ13', current_timestamp),
  ('book', 'BPRSS13', current_timestamp),
  ('book', 'ILS13', current_timestamp),
  ('book', 'DLSV13', current_timestamp),
  ('book', 'CRSW13', current_timestamp),
  ('book', 'HSS13', current_timestamp),
  ('book', 'ALS13', current_timestamp),
  ('book', 'PSV13', current_timestamp),
  ('book', 'BLLMSS13', current_timestamp),
  ('book', 'LS12', current_timestamp),
  ('book', 'DHS12', current_timestamp),
  ('book', 'MPS12,', current_timestamp),
  ('book', 'SS12', current_timestamp),
  ('book', 'PST12,', current_timestamp),
  ('book', 'CDS12,', current_timestamp),
  ('book', 'DS11,', current_timestamp),
  ('book', 'LMS11', current_timestamp),
  ('book', 'BPSS11', current_timestamp),
  ('book', 'HSV10a,', current_timestamp),
  ('book', 'MS10a', current_timestamp),
  ('book', 'FPRS10a,', current_timestamp),
  ('book', 'MST10,', current_timestamp),
  ('book', 'PS10,', current_timestamp),
  ('book', 'CDS10,', current_timestamp),
  ('book', 'CDRS09,', current_timestamp),
  ('book', 'PSE09,', current_timestamp),
  ('book', 'BRS09,', current_timestamp),
  ('book', 'PPS09', current_timestamp),
  ('book', 'PSW09,', current_timestamp),
  ('book', 'PSZ09,', current_timestamp),
  ('book', 'BRSV08', current_timestamp),
  ('book', 'AJSV08,', current_timestamp),
  ('book', 'AJS08,', current_timestamp),
  ('book', 'PSZ07,', current_timestamp),
  ('book', 'HSV07,', current_timestamp),
  ('book', 'PS07,', current_timestamp),
  ('book', 'AHSV07,', current_timestamp),
  ('book', 'LMS07,', current_timestamp),
  ('book', 'BKS06', current_timestamp),
  ('book', 'HSVW05,', current_timestamp),
  ('book', 'PS05b,', current_timestamp),
  ('book', 'PS05a', current_timestamp),
  ('book', 'KS04,', current_timestamp),
  ('book', 'SWV04,', current_timestamp),
  ('book', 'KPS04,', current_timestamp),
  ('book', 'GKS04', current_timestamp),
  ('book', 'HMS03,', current_timestamp),
  ('book', 'PS03,', current_timestamp),
  ('book', 'HSS03,', current_timestamp),
  ('book', 'SS02b,', current_timestamp),
  ('book', 'SS02a,', current_timestamp),
  ('book', 'KSTT02,', current_timestamp),
  ('book', 'MS02,', current_timestamp),
  ('book', 'HMS02,', current_timestamp),
  ('book', 'MSH02', current_timestamp),
  ('book', 'ES02,', current_timestamp),
  ('book', 'SSW01,', current_timestamp),
  ('book', 'CS01,', current_timestamp),
  ('book', 'CSSW01,', current_timestamp),
  ('book', 'SS00,', current_timestamp),
  ('book', 'SW99,', current_timestamp),
  ('book', 'GHS99,', current_timestamp),
  ('book', 'SS99,', current_timestamp),
  ('book', 'LS98,', current_timestamp),
  ('book', 'JST98,', current_timestamp),
  ('book', 'GS98,', current_timestamp),
  ('book', 'BKS98,', current_timestamp),
  ('book', 'HS98,', current_timestamp),
  ('book', 'S97', current_timestamp),
  ('book', 'BS97,', current_timestamp),
  ('book', 'ES96', current_timestamp),
  ('book', 'JS95,', current_timestamp),
  ('book', 'SH95,', current_timestamp),
  ('book', 'LS95,', current_timestamp),
  ('book', 'ES95,', current_timestamp),
  ('book', 'BEGSS95', current_timestamp),
  ('book', 'BSS94,', current_timestamp),
  ('book', 'SH94,', current_timestamp),
  ('book', 'HS94,', current_timestamp),
  ('book', 'BDS94,', current_timestamp),
  ('book', 'BSS93,', current_timestamp),
  ('book', 'BDS93', current_timestamp),
  ('book', 'ES93,', current_timestamp),
  ('book', 'CS93,', current_timestamp),
  ('book', 'SS92', current_timestamp),
  ('book', 'GSY92,', current_timestamp),
  ('book', 'IS92,', current_timestamp),
  ('book', 'CS91,', current_timestamp),
  ('book', 'IPS91,', current_timestamp),
  ('book', 'SP91,', current_timestamp),
  ('book', 'S91,', current_timestamp),
  ('book', 'SF90,', current_timestamp),
  ('book', 'S89d,', current_timestamp),
  ('book', 'NS89', current_timestamp),
  ('book', 'S89c,', current_timestamp),
  ('book', 'S89b,', current_timestamp),
  ('book', 'S89a,', current_timestamp),
  ('book', 'S88,', current_timestamp),
  ('book', 'NS88c', current_timestamp),
  ('book', 'NS88b', current_timestamp),
  ('book', 'NS88a', current_timestamp),
  ('book', 'S87,', current_timestamp),
  ('book', 'NS87b,', current_timestamp),
  ('book', 'NS87a,', current_timestamp),
  ('book', 'SV10a', current_timestamp),
  ('book', 'LSZ15', current_timestamp),
  ('book', 'PS08', current_timestamp),
  ('book', 'GS08', current_timestamp),
  ('book', 'SH96', current_timestamp),
  ('book', 'BS16', current_timestamp),
  ('book', 'RS15', current_timestamp),
  ('book', 'DS15', current_timestamp),
  ('book', 'IS14', current_timestamp),
  ('book', 'PPS10a', current_timestamp),
  ('book', 'NPS10a', current_timestamp),
  ('book', 'HSV11', current_timestamp),
  ('book', 'S10a', current_timestamp),
  ('book', 'WS09', current_timestamp),
  ('book', 'BS09', current_timestamp),
  ('book', 'BS08', current_timestamp),
  ('book', 'HSV08', current_timestamp),
  ('book', 'PSB06', current_timestamp),
  ('book', 'HS01', current_timestamp),
  ('book', 'SS01', current_timestamp),
  ('book', 'LS99', current_timestamp),
  ('book', 'S96', current_timestamp),
  ('book', 'S95', current_timestamp),
  ('book', 'S94', current_timestamp),
  ('book', 'HJS94', current_timestamp),
  ('book', 'S90', current_timestamp),
  ('book', 'S88', current_timestamp);

INSERT INTO field (reference_id, name, content) VALUES
  (1, 'author', 'S.N.Gomes and A.M.Stuart and M-T.Wolfram'),
  (1, 'title', 'Parameter Estimation for Macroscopic Pedestrian Dynamics Models from Microscopic Data'),
  (1, 'note', 'submitted'),
  (2, 'author', 'N.B.Kovachki and A.M.Stuart'),
  (2, 'title', 'Ensemble Kalman Inversion: A Derivative-Free Technique For Machine Learning Tasks'),
  (2, 'note', 'submitted'),
  (3, 'author', 'M.M.Dunlop and D.Slepcev and A.M.Stuart and M.Thorpe'),
  (3, 'title', 'Large Data and Zero Noise Limits of Graph-Based Semi-Supervised Learning Algorithms'),
  (3, 'note', 'submitted'),
  (4, 'author', 'V.Chen and M.M.Dunlop and O.Papaspiliopoulos and A.M.Stuart'),
  (4, 'title', 'Robust MCMC Sampling with Non-Gaussian and Hierarchical Priors in High Dimensions'),
  (4, 'note', 'submitted'),
  (5, 'author', 'M.M.Dunlop and M.Girolami and A.M.Stuart and A.L.Teckentrup'),
  (5, 'title', 'How Deep are Deep Gaussian Processes?'),
  (5, 'note', 'submitted'),
  (6, 'author', 'M.E.Levine and G.Hripcsak and L.Mamykina and A.Stuart and D.J.Albers'),
  (6, 'title', 'Offline and online data assimilation for real-time blood glucose forecasting in type 2 diabetes'),
  (6, 'note', 'submitted'),
  (7, 'author', 'M.M.Dunlop and C.M.Elliott and V.H.Hoang and A.M. Stuart'),
  (7, 'title', 'Bayesian Formulations of Multidimensional Barcode Inversion'),
  (7, 'note', 'submitted'),
  (8, 'author', 'C.Schillings and A.M. Stuart'),
  (8, 'title', 'Convergence Analysis of the Ensemble Kalman Filter for Inverse Problems: the Noisy Case'),
  (8, 'note', 'submitted'),
  (9, 'author', 'H.C.Lie and A.M. Stuart and T.J.Sullivan'),
  (9, 'title', 'Strong convergence rates of probabilistic integrators for ordinary differential equations'),
  (9, 'note', 'submitted'),
  (10, 'author', 'D. Kelly and A.M. Stuart'),
  (10, 'title', 'Ergodicity and Accuracy of Optimal Particle Filters for Bayesian Data Assimilation'),
  (10, 'note', 'submitted'),
  (11, 'author', 'M. Ottobre and A.M. Stuart and J.Kuntz'),
  (11, 'title', 'Diffusion limit for the random walk Metropolis algorithm out of stationarity'),
  (11, 'journal', 'Annales de l''Institut Henri Poincare B'),
  (11, 'note', 'to appear'),
  (12, 'author', 'D. Bloemker and K.J.H. Law and A.M. Stuart and K. Zygalalkis'),
  (12, 'title', 'Accuracy and stability of the continuous-time 3DVAR filter for the Navier-Stokes equation'),
  (12, 'note', 'Submitted'),
  (12, 'arXiv', 'arXiv:1210.1594'),
  (13, 'author', 'N.S.Pillai and A.M. Stuart and A.H.Thiery'),
  (13, 'title', 'Gradient Flow from a random walk in Hilbert space'),
  (13, 'note', 'Submitted'),
  (13, 'arXiv', 'arXiv:1108.1494'),
  (14, 'author', 'A. Beskos and N. Pillai and G.O. Roberts and J.-M. Sanz-Serna and A.M. Stuart'),
  (14, 'title', 'Optimal tuning of hybrid Monte-Carlo'),
  (14, 'journal', 'Bernoulli'),
  (14, 'note', 'to appear'),
  (14, 'arXiv', 'arXiv:1001.4460'),
  (15, 'author', 'A.L.Bertozzi and X.Luo and A.M.Stuart and K.C.Zygalakis'),
  (15, 'title', 'Uncertainty Quantification in the Classification of High Dimensional Data'),
  (15, 'journal', 'SIAM-ASA JUQ'),
  (15, 'year', '2018'),
  (15, 'volume', '6'),
  (15, 'issue', '2'),
  (15, 'pages', '568-595'),
  (15, 'DOI', '10.1137/17M1134214'),
  (16, 'author', 'N.K.Chada and M.A.Iglesias and L.Roininen and A.M.Stuart'),
  (16, 'title', 'Parameterizations for Ensemble Kalman Inversion'),
  (16, 'journal', 'Inverse Problems'),
  (16, 'year', '2018'),
  (16, 'volume', '34'),
  (16, 'pages', '055009'),
  (16, 'DOI', '10.1088/1361-6420/aab6d9'),
  (17, 'author', 'J. Kuntz and M. Ottobre and A.M. Stuart'),
  (17, 'title', 'Non-stationary phase of the MALA algorithm'),
  (17, 'journal', 'Stochastic PDE: Anal Comp.'),
  (17, 'year', '2018'),
  (17, 'DOI', '10.1007/s40072-018-0113-1'),
  (18, 'author', 'D.Calvetti and M.M.Dunlop and E.Somersalo and A.M.Stuart'),
  (18, 'title', 'Iterative Updating of Model Error for Bayesian Inversion'),
  (18, 'journal', 'Inverse Problems'),
  (18, 'year', '2018'),
  (18, 'volume', '34'),
  (18, 'pages', '025008'),
  (18, 'DOI', '10.1088/1361-6420/aaa34d'),
  (19, 'author', 'A.M.Stuart and A.L.Teckentrup'),
  (19, 'title', 'Posterior consistency for Gaussian process approximations of Bayesian posterior distributions.'),
  (19, 'journal', 'Mathematics of Computation'),
  (19, 'year', '2018'),
  (19, 'volume', '87'),
  (19, 'issue', '310'),
  (19, 'pages', '721-753'),
  (19, 'DOI', '10.1090/mcom/3244'),
  (21, 'author', 'Y. Lu and A.M. Stuart and H. Weber'),
  (21, 'title', 'Gaussian approximations for transition paths in Brownian dynamics'),
  (21, 'journal', 'SIAM J. MATH. ANAL.'),
  (21, 'year', '2017'),
  (21, 'volume', '49'),
  (21, 'issue', '4'),
  (21, 'pages', '3005-3047'),
  (21, 'DOI', '10.1137/16M1071845'),
  (22, 'author', 'Y. Lu and A.M. Stuart and H. Weber'),
  (22, 'title', 'Gaussian Approximations for Probability Measures on Rd'),
  (22, 'journal', 'SIAM/ASA J. UNCERTAINTY QUANTIFICATION'),
  (22, 'year', '2017'),
  (22, 'volume', '5'),
  (22, 'pages', '1136-1165'),
  (22, 'DOI', '10.1137/16M1105384'),
  (23, 'author', 'T.Schneider and S.Lan and A.Stuart and J.Teixeira'),
  (23, 'title', 'Earth System Modeling 2.0: A Blueprint for Models That Learn From Observations and Targeted High-Resolution Simulations'),
  (23, 'journal', 'Geophysical Research Letters'),
  (23, 'year', '2017'),
  (23, 'volume', '44'),
  (23, 'DOI', '10.1002/2017GL076101'),
  (24, 'author', 'D. Sanz-Alonso and A.M. Stuart'),
  (24, 'title', 'Gaussian approximations of small noise diffusions in Kullback-Leibler divergence'),
  (24, 'journal', 'Communications in Mathematical Sciences'),
  (24, 'year', '2017'),
  (24, 'volume', '15'),
  (24, 'issue', '7'),
  (24, 'pages', '2087-2097'),
  (24, 'DOI', '10.4310/CMS.2017.v15.n7.a13'),
  (25, 'author', 'M.A. Iglesias and K. Lin and S. Lu and A.M. Stuart'),
  (25, 'title', 'Filter based methods for statistical linear inverse problems'),
  (25, 'journal', 'Communications in Mathematical Sciences'),
  (25, 'year', '2017'),
  (25, 'volume', '15'),
  (25, 'issue', '7'),
  (25, 'pages', '1867-1896'),
  (25, 'DOI', '10.4310/CMS.2017.v15.n7.a4'),
  (26, 'author', 'S. Agapiou and O. Papaspiliopoulos and D. Sanz-Alonso and A. M. Stuart'),
  (26, 'title', 'Importance sampling: computational complexity and intrinsic dimension'),
  (26, 'journal', 'Statistical Science'),
  (26, 'year', '2017'),
  (26, 'volume', '32'),
  (26, 'issue', '3'),
  (26, 'pages', '405-431'),
  (26, 'DOI', '10.1214/17-STS611'),
  (27, 'author', 'C.Schillings and A.M.Stuart'),
  (27, 'title', 'Analysis of the ensemble Kalman filter for inverse problems.'),
  (27, 'journal', 'SINUM'),
  (27, 'year', '2017'),
  (27, 'volume', '55'),
  (27, 'issue', '3'),
  (27, 'pages', '1264-1290'),
  (27, 'DOI', '10.1137/16M105959X'),
  (28, 'author', 'A. Beskos and M. Girolami and S. Lan and P.E. Farrell and A.M. Stuart'),
  (28, 'title', 'Geometric MCMC for Infinite-Dimensional Inverse Problems'),
  (28, 'journal', 'Journal of Computational Physics'),
  (28, 'year', '2017'),
  (28, 'volume', '335'),
  (28, 'pages', '327-351'),
  (29, 'author', 'R.Scheichl and A.M.Stuart and A.L.Teckentrup'),
  (29, 'title', 'Quasi Monte-Carlo and multi-level Monte Carlo for computing posterior expectations in elliptic inverse problems.'),
  (29, 'journal', 'JUQ'),
  (29, 'year', '2017'),
  (29, 'volume', '5'),
  (29, 'issue', '1'),
  (29, 'pages', '493-518'),
  (29, 'DOI', '10.1137/16M1061692'),
  (30, 'author', 'W.Lee and A.M. Stuart'),
  (30, 'title', 'Derivation and analysis of simplified filters for complex dynamical systems'),
  (30, 'journal', 'Communications in Mathematical Sciences'),
  (30, 'year', '2017'),
  (30, 'volume', '15'),
  (30, 'issue', '2'),
  (30, 'pages', '413-450'),
  (30, 'DOI', '10.4310/CMS.2017.v15.n2.a6'),
  (31, 'author', 'M. Iglesias and Y. Lu and A.M. Stuart'),
  (31, 'title', 'A Bayesian level set method for geometric inverse problems'),
  (31, 'journal', 'Interfaces and Free Boundaries'),
  (31, 'year', '2016'),
  (31, 'volume', '18'),
  (31, 'issue', '2'),
  (31, 'pages', '181-217'),
  (31, 'DOI', '10.4171/IFB/362'),
  (32, 'author', 'M.M.Dunlop and A.M.Stuart'),
  (32, 'title', 'The Bayesian formulation of EIT: analysis and algorithms'),
  (32, 'journal', 'Inverse Problems and Imaging'),
  (32, 'year', '2016'),
  (32, 'volume', '10'),
  (32, 'issue', '4'),
  (32, 'pages', '1007-1036'),
  (32, 'DOI', '10.3934/ipi.2016030'),
  (33, 'author', 'M.M.Dunlop and M.A.Iglesias and A.M.Stuart'),
  (33, 'title', 'Hierarchical Bayesian level set inversion'),
  (33, 'journal', 'Statistics and Computing'),
  (33, 'year', '2016'),
  (33, 'DOI', '10.1007/s11222-016-9704-8'),
  (34, 'author', 'M.M.Dunlop and A.M.Stuart'),
  (34, 'title', 'MAP estimators for piecewise continuous inversion'),
  (34, 'journal', 'Inverse Problems'),
  (34, 'year', '2016'),
  (34, 'volume', '32'),
  (34, 'issue', '10'),
  (34, 'pages', '105003'),
  (34, 'DOI', '10.1088/0266-5611/32/10/105003'),
  (35, 'author', 'P.R.Conrad and M.Girolami and S.Sarkka and A.M.Stuart and K.C.Zygalakis'),
  (35, 'title', 'Statistical analysis of differential equations: introducing probability measures on numerical solutions'),
  (35, 'journal', 'Statistics and Computing'),
  (35, 'year', '2016'),
  (35, 'DOI', '10.1007/s11222-016-9671-0'),
  (36, 'author', 'K.J.H. Law and D. Sanz-Alonso and A. Shukla and A.M. Stuart'),
  (36, 'title', 'Filter accuracy for the Lorenz 96 model: fixed versus adaptive observation operators'),
  (36, 'journal', 'Physica D: Nonlinear Phenomena'),
  (36, 'year', '2016'),
  (36, 'volume', '325'),
  (36, 'pages', '1-13'),
  (36, 'DOI', 'doi:10.1016/j.physd.2015.12.008'),
  (37, 'author', 'M. Ottobre and N.S.Pillai and F.J. Pinski and A.M.Stuart'),
  (37, 'title', 'A Function Space HMC Algorithm With Second Order Langevin Diffusion Limit'),
  (37, 'journal', 'Bernoulli'),
  (37, 'year', '2016'),
  (37, 'volume', '22'),
  (37, 'issue', '1'),
  (37, 'pages', '60-106'),
  (37, 'DOI', '10.3150/14-BEJ621'),
  (38, 'author', 'F..J. Pinski and G. Simpson and A.M. Stuart and H. Weber'),
  (38, 'title', 'Algorithms for Kullback-Leibler approximation for probability measures in infinite dimensions'),
  (38, 'journal', 'SIAM Journal on Scientific Computing'),
  (38, 'year', '2015'),
  (38, 'volume', '37'),
  (38, 'issue', '6'),
  (38, 'pages', 'A2733-A2757'),
  (38, 'DOI', '10.1137/14098171X'),
  (39, 'author', 'D. Sanz-Alonso and A. M. Stuart'),
  (39, 'title', 'Long-Time Asymptotics of the Filtering Distribution for Partially Observed Chaotic Dynamical Systems'),
  (39, 'journal', 'SIAM/ASA J. Uncertainty Quantification'),
  (39, 'year', '2015'),
  (39, 'volume', '3'),
  (39, 'issue', '1'),
  (39, 'pages', '1200-1220'),
  (39, 'DOI', '10.1137/140997336'),
  (40, 'author', 'F.J. Pinski and G. Simpson and A.M. Stuart and H. Weber'),
  (40, 'title', 'Kullback-Leibler approximation for probability measures on infinite dimensional spaces'),
  (40, 'journal', 'SIAM J. Mathematical Analysis'),
  (40, 'year', '2015'),
  (40, 'volume', '47'),
  (40, 'issue', '6'),
  (40, 'pages', '4091-4122'),
  (40, 'DOI', '10.1137/140962802'),
  (41, 'author', 'A.Beskos and A. Jasra and E. Muzaffer and A.M. Stuart'),
  (41, 'title', 'Sequential Monte Carlo methods for Bayesian elliptic inverse problems'),
  (41, 'journal', 'Stat. Comp.'),
  (41, 'year', '2015'),
  (41, 'volume', '25'),
  (41, 'pages', '727-737'),
  (41, 'DOI', '10.1007/s11222-015-9556-7'),
  (42, 'author', 'A. B. Duncan and C. M. Elliot and G. A. Pavliotis and A. M. Stuart'),
  (42, 'title', 'A multiscale analysis of diffusions on rapidly varying surfaces'),
  (42, 'journal', 'Journal of Nonlinear Science'),
  (42, 'year', '2015'),
  (42, 'volume', '25'),
  (42, 'issue', '2'),
  (42, 'pages', '389-449'),
  (42, 'DOI', '10.1007/s00332-015-9237-x'),
  (43, 'author', 'M.A. Iglesias and K. Lin and A.M. Stuart'),
  (43, 'title', 'Well-posed Bayesian geometric inverse problems arising in subsurface flow'),
  (43, 'journal', 'Inverse Problems'),
  (43, 'year', '2014'),
  (43, 'volume', '30'),
  (43, 'pages', '114001'),
  (43, 'DOI', 'doi:10.1088/0266-5611/30/11/114001'),
  (44, 'author', 'S. Agapiou and J.M. Bardsley and O. Papaspiliopoulos and A. M. Stuart'),
  (44, 'title', 'Analysis of the Gibbs sampler for hierarchical inverse problems'),
  (44, 'journal', 'Journal on Uncertainty Quantification'),
  (44, 'year', '2014'),
  (44, 'volume', '2'),
  (44, 'pages', '511-544'),
  (44, 'DOI', 'DOI: 10.1137/130944229'),
  (45, 'author', 'D.T.B. Kelly and K.J.H. Law and A.M. Stuart'),
  (45, 'title', 'Well-posedness and accuracy of the ensemble Kalman filter In discrete and continuous time'),
  (45, 'journal', 'Nonlinearity'),
  (45, 'year', '2014'),
  (45, 'volume', '27'),
  (45, 'pages', '2579-2603'),
  (45, 'DOI', 'doi:10.1088/0951-7715/27/10/2579'),
  (46, 'author', 'M. Hairer and A.M. Stuart and S.J. Vollmer'),
  (46, 'title', 'Spectral gaps for Metropolis-Hastings algorithms in infinite dimensions'),
  (46, 'journal', 'The Annals of Applied Probability'),
  (46, 'year', '2014'),
  (46, 'volume', '24'),
  (46, 'pages', '2455-290'),
  (46, 'DOI', '10.1214/13-AAP982'),
  (47, 'author', 'N.S.Pillai and A.M. Stuart and A.H. Thiery'),
  (47, 'title', 'Noisy gradient flow from a random walk in Hilbert space'),
  (47, 'journal', 'Stochastic PDEs: Analysis and Computation'),
  (47, 'year', '2014'),
  (47, 'volume', '2'),
  (47, 'pages', '196-232'),
  (47, 'DOI', '10.1007/s40072-014-0029-3'),
  (48, 'author', 'V. H Hoang and K.J.H. Law and A.M. Stuart'),
  (48, 'title', 'Determining white noise forcing from Eulerian observations in the Navier-Stokes equation'),
  (48, 'journal', 'Stochastic PDEs: Analysis and Computation'),
  (48, 'year', '2014'),
  (48, 'volume', '2'),
  (48, 'pages', '233-261'),
  (48, 'DOI', '10.1007/s40072-014-0028-4'),
  (49, 'author', 'S. Agapiou and A.M. Stuart and Y-X. Zhang'),
  (49, 'title', 'Bayesian posterior contraction rates for linear severely ill-posed inverse problems'),
  (49, 'journal', 'Journal of Inverse and Ill-Posed Problems'),
  (49, 'year', '2014'),
  (49, 'volume', '22'),
  (49, 'pages', '297-321'),
  (49, 'DOI', '10.1515/jip-2012-0071'),
  (49, 'arXiv', 'arXiv:1210.1563'),
  (50, 'author', 'K.J.H. Law and A. Shukla and A.M. Stuart'),
  (50, 'title', 'Analysis of the 3DVAR Filter for the Partially Observed Lorenz ''63 Model'),
  (50, 'journal', 'Discrete and Continuous Dynamical Systems A'),
  (50, 'year', '2014'),
  (50, 'volume', '34'),
  (50, 'pages', '1061-1078'),
  (50, 'DOI', '10.3934/dcds.2014.34.1061'),
  (50, 'arXiv', 'arXiv:'),
  (51, 'author', 'D. Bloemker and K.J.H. Law and A.M. Stuart and K. Zygalalkis'),
  (51, 'title', 'Accuracy and stability of the continuous-time 3DVAR filter for the Navier-Stokes equation'),
  (51, 'journal', 'Nonlinearity'),
  (51, 'year', '2013'),
  (51, 'volume', '26'),
  (51, 'pages', '2193-2219'),
  (51, 'DOI', '10.1088/0951-7715/26/8/2193'),
  (51, 'arXiv', 'arXiv:'),
  (52, 'author', 'A. Beskos and N. Pillai and G.O. Roberts and J.-M. Sanz-Serna and A.M. Stuart'),
  (52, 'title', 'Optimal tuning of hybrid Monte Carlo algorithm'),
  (52, 'journal', 'Bernoulli'),
  (52, 'year', '2013'),
  (52, 'volume', '19'),
  (52, 'pages', '1501-1534'),
  (52, 'DOI', '10.3150/12-BEJ414'),
  (52, 'arXiv', 'arXiv:1001.4460'),
  (53, 'author', 'M.A. Iglesias, K.J.H. Law and A.M. Stuart'),
  (53, 'title', 'Evaluation of Gaussian approximations for data assimilation in reservoir models'),
  (53, 'journal', 'Computational Geosciences'),
  (53, 'year', '2013'),
  (53, 'volume', '17'),
  (53, 'pages', '851-885'),
  (53, 'DOI', '10.1007/s10596-013-9359-x'),
  (53, 'arXiv', 'arXiv:1212.1779'),
  (54, 'author', 'M. Dashti and K.J.H. Law and A.M. Stuart and J. Voss'),
  (54, 'title', 'MAP estimators and posterior consistency in Bayesian nonparametric inverse problems'),
  (54, 'journal', 'Inverse Problems'),
  (54, 'year', '2013'),
  (54, 'volume', '29'),
  (54, 'pages', '095017'),
  (54, 'DOI', ''),
  (54, 'arXiv', 'arXiv:'),
  (55, 'author', 'S.L.Cotter and G.O.Roberts and A.M. Stuart and D. White'),
  (55, 'title', 'MCMC methods for functions: modifying old algorithms to make them faster'),
  (55, 'journal', 'Statistical Science'),
  (55, 'year', '2013'),
  (55, 'volume', '28'),
  (55, 'pages', '424-446'),
  (55, 'DOI', ''),
  (55, 'arXiv', 'arXiv:'),
  (56, 'author', 'V.H. Hoang and C. Schwab and A.M. Stuart'),
  (56, 'title', 'Complexity analysis of accelerated MCMC methods for Bayesian inversion'),
  (56, 'journal', 'Inverse Problems'),
  (56, 'year', '2013'),
  (56, 'volume', '29'),
  (56, 'number', '8'),
  (56, 'pages', '085010'),
  (56, 'DOI', '10.1088/0266-5611/29/8/085010'),
  (56, 'arXiv', 'arXiv:1207.2411'),
  (57, 'author', 'S.Agapiou and S.Larsson and A.M. Stuart'),
  (57, 'title', 'Posterior consistency of the Bayesian approach to linear ill-posed inverse problems'),
  (57, 'journal', 'Stochastic Processes and their Applications'),
  (57, 'year', '2013'),
  (57, 'volume', '123'),
  (57, 'number', '10'),
  (57, 'pages', '3828-3860'),
  (57, 'DOI', '10.1016/j.spa.2013.05.001'),
  (57, 'arXiv', 'arXiv:1203.5753'),
  (58, 'author', 'Y.Pokern and A.M. Stuart and J.H. Van Zanten'),
  (58, 'title', 'Posterior consistency via precision operators for nonparametric drift estimation in SDEs'),
  (58, 'journal', 'Stochastic Processes and Their Applications'),
  (58, 'year', '2013'),
  (58, 'voume', '123'),
  (58, 'number', '2'),
  (58, 'pages', '603-628'),
  (58, 'DOI', '10.1016/j.spa.2012.08.010'),
  (58, 'arXiv', 'arXiv:1202.0976'),
  (59, 'author', 'M.A. Iglesias and K.J.H. Law and A.M. Stuart'),
  (59, 'title', 'The ensemble Kalman filter for inverse problems'),
  (59, 'journal', 'Inverse Problems'),
  (59, 'year', '2013'),
  (59, 'volume', '29'),
  (59, 'number', '4'),
  (59, 'pages', '045001'),
  (59, 'DOI', 'doi:10.1088/0266-5611/29/4/045001'),
  (59, 'arXiv', 'arXiv:1209.2736'),
  (60, 'author', 'C.E.A. Brett and K.F. Lam and K.J.H. Law and D.S. McCormick and M.R. Scott and A.M. Stuart'),
  (60, 'title', 'Accuracy and stability of filters for the Navier-Stokes equation'),
  (60, 'journal', 'Physica D'),
  (60, 'year', '2013'),
  (60, 'volume', '245'),
  (60, 'pages', '34-45'),
  (60, 'arXiv', 'arXiv:1110.2527'),
  (61, 'author', 'Natesh S. Pillai and Andrew M. Stuart and Alexandre H. Thiéry'),
  (61, 'title', 'Optimal scaling and diffusion limits for the Langevin algorithm in high dimensions'),
  (61, 'journal', 'Annals of Applied Probability'),
  (61, 'fjournal', 'Annals of Applied Probability'),
  (61, 'year', '2012'),
  (61, 'volume', '22'),
  (61, 'number', '6'),
  (61, 'pages', '2320-2356'),
  (61, 'ISSN', '1050-5164'),
  (61, 'DOI', '10.1214/11-AAP828'),
  (61, 'arXiv', '1103.0542'),
  (61, 'SICI', '1050-5164(2012)22:6<2320:OSADLF>2.0.CO;2-4'),
  (62, 'author', 'K.Law and A.M. Stuart'),
  (62, 'title', 'Evaluating data assimilation algorithms'),
  (62, 'journal', 'Monthly Weather Review'),
  (62, 'volume', '140'),
  (62, 'year', '2012'),
  (62, 'pages', '3757-3782'),
  (62, 'arXiv', 'arXiv:1107.4118'),
  (63, 'author', 'O. Papspilioupoulis and Y. Pokern and G.O. Roberts and A.M.Stuart'),
  (63, 'title', 'Nonparametric estimation of diffusions: a differential equations approach'),
  (63, 'journal', 'Biometrika'),
  (63, 'year', '2012'),
  (63, 'doi', '10.1093/biomet/ass034'),
  (64, 'author', 'M.Dashti and S. Harris and A.M.Stuart'),
  (64, 'title', 'Besov priors for Bayesian inverse problems'),
  (64, 'journal', 'Inverse Problems and Imaging'),
  (64, 'volume', '6'),
  (64, 'year', '2012'),
  (64, 'pages', '183-200'),
  (64, 'arXiv', 'arXiv:1105.0889'),
  (65, 'author', 'J.C. Mattingly and N. Pillai and A.M. Stuart'),
  (65, 'title', 'Diffusion limits of random walk Metropolis algorithms in high dimensions'),
  (65, 'journal', 'Annals of Applied Probability'),
  (65, 'volume', '22'),
  (65, 'year', '2012'),
  (65, 'pages', '881-930'),
  (65, 'arXiv', 'arXiv:1003.4306'),
  (66, 'author', 'Ch. Schwab and A.M. Stuart'),
  (66, 'title', 'Sparse deterministic approximation of Bayesian inverse problems'),
  (66, 'journal', 'Inverse Problems'),
  (66, 'volume', '28'),
  (66, 'year', '2012'),
  (66, 'pages', '045003'),
  (67, 'author', 'F. Pinskii and A.M.Stuart and F. Theil'),
  (67, 'title', 'Gamma limits for transition paths of maximal probability'),
  (67, 'journal', 'J. Stat. Phys.'),
  (67, 'volume', '146'),
  (67, 'year', '2012'),
  (68, 'author', 'S.L.Cotter and M. Dashti and A.M.Stuart'),
  (68, 'title', 'Variational data assimilation using targetted random walks'),
  (68, 'journal', 'Int. J. Num. Meth. Fluids'),
  (68, 'volume', '68'),
  (68, 'year', '2012'),
  (68, 'pages', 403-421),
  (69, 'author', 'M.Dashti and A.M.Stuart'),
  (69, 'title', 'Uncertainty quantification and weak approximation of an elliptic inverse problem'),
  (69, 'journal', 'SIAM J. Numerical Analysis'),
  (69, 'volume', '49'),
  (69, 'year', '2011'),
  (69, 'pages', '2524--2542'),
  (70, 'author', 'W.Lee and D.McDougall and A.M.Stuart'),
  (70, 'title', 'Kalman filtering for linear wave equations with model error'),
  (70, 'journal', 'Inverse Problems'),
  (70, 'volume', '27'),
  (70, 'year', '2011'),
  (70, 'pages', '095008'),
  (71, 'author', 'A. Beskos and F. Pinski and J.M. Sanz-Serna and A.M.Stuart'),
  (71, 'title', 'Hybrid Monte-Carlo on Hilbert Spaces'),
  (71, 'journal', 'Stochastic Processes and Applications'),
  (71, 'volume', '121'),
  (71, 'year', '2011'),
  (71, 'pages', '2201-2230'),
  (72, 'author', 'M. Hairer and A.M. Stuart and J. Voss'),
  (72, 'title', 'Sampling conditioned hypoelliptic diffusions'),
  (72, 'journal', 'Annals of Applied Probability'),
  (72, 'volume', '2011'),
  (72, 'year', '2011'),
  (72, 'pages', '669-698'),
  (73, 'author', 'I. Melbourne and A.M.Stuart'),
  (73, 'title', 'A Note on Diffusion Limits of Chaotic Skew Product Flows'),
  (73, 'journal', 'Nonlinearity'),
  (73, 'volume', '24'),
  (73, 'year', '2011'),
  (73, 'pages', '1361--1367'),
  (74, 'author', 'P. Fearnhead and O. Papaspiliopoulos and G.O. Roberts and A.M. Stuart'),
  (74, 'title', 'Random-weight particle filtering of continuous time stochastic processes'),
  (74, 'journal', 'Journal of the Royal Statistical Society B'),
  (74, 'volume', '72'),
  (74, 'issue', '4'),
  (74, 'year', '2010'),
  (74, 'pages', '497-512'),
  (75, 'author', 'J.C. Mattingly and A.M. Stuart and M. Tretyakov'),
  (75, 'title', 'Convergence of numerical time-averaging and stationary measures via the Poisson equation'),
  (75, 'journal', 'SIAM Journal of Numerical Analysis'),
  (75, 'volume', '48'),
  (75, 'issue', '2'),
  (75, 'year', '2010'),
  (75, 'pages', '552-577'),
  (76, 'author', 'F.J. Pinski and A.M. Stuart'),
  (76, 'title', 'Transition paths in molecules: gradient descent in pathspace'),
  (76, 'journal', 'Journal of Chemical Physics'),
  (76, 'volume', '132'),
  (76, 'year', '2010'),
  (76, 'pages', '184104'),
  (77, 'author', 'S.L. Cotter and M. Dashti and A.M. Stuart'),
  (77, 'title', 'Approximation of Bayesian Inverse Problems'),
  (77, 'journal', 'SIAM Journal of Numerical Analysis'),
  (77, 'volume', '48'),
  (77, 'year', '2010'),
  (77, 'pages', '322-345'),
  (78, 'author', 'S.L. Cotter and M. Dashti and J.C. Robinson and A.M Stuart'),
  (78, 'title', 'Bayesian inverse problems for functions and applications to fluid mechanics'),
  (78, 'journal', 'Inverse Problems'),
  (78, 'volume', '25'),
  (78, 'year', '2009'),
  (78, 'pages', '115008'),
  (79, 'author', 'Y. Pokern and A.M. Stuart and E. Vanden Eijnden'),
  (79, 'title', 'Remarks on Drift Estimation for Diffusion Processes'),
  (79, 'journal', 'SIAM Multiscale Modeling Simulation'),
  (79, 'volume', '8'),
  (79, 'year', '2009'),
  (79, 'pages', '69-95'),
  (80, 'author', 'A. Beskos and G.O. Roberts and A.M. Stuart'),
  (80, 'title', 'Optimal scalings of Metropolis-Hastings algorithms for non-product targets in high dimensions'),
  (80, 'journal', 'Annals of Applied Probability'),
  (80, 'volume', '19'),
  (80, 'year', '2009'),
  (80, 'pages', '863-898'),
  (81, 'author', 'A. Papavasiliou and G. Pavliotis and A.M. Stuart'),
  (81, 'title', 'Maximum likelihood estimation for multiscale diffusions'),
  (81, 'journal', 'Stochastic Processes and their Applications'),
  (81, 'volume', '19'),
  (81, 'year', '2009'),
  (81, 'pages', '3173-3210'),
  (82, 'author', 'Y. Pokern and A.M. Stuart and P. Wiberg'),
  (82, 'title', 'Parameter estimation for partially observed hypo-elliptic diffusions'),
  (82, 'journal', 'Journal of the Royal Statistical Society B'),
  (82, 'volume', '71'),
  (82, 'year', '2009'),
  (82, 'pages', '49-73'),
  (83, 'author', 'G. Pavliotis and A.M. Stuart, and K. Zygalakis'),
  (83, 'title', 'Calculating effective diffusivities in the limit of vanishing molecular diffusion'),
  (83, 'journal', 'Journal of Computational Physics'),
  (83, 'volume', '228'),
  (83, 'year', '2009'),
  (83, 'pages', '1030-1055'),
  (84, 'author', 'A. Beskos and G. Roberts and A.M. Stuart and J. Voss'),
  (84, 'title', 'An MCMC method for diffusion bridges'),
  (84, 'journal', 'Stochastics and Dynamics'),
  (84, 'volume', '8'),
  (84, 'year', '2008'),
  (84, 'pages', '319-350'),
  (85, 'author', 'A. Apte and C.K.R.T. Jones and A.M. Stuart and J. Voss'),
  (85, 'title', 'Data assimilation: mathematical and statistical perspectives'),
  (85, 'journal', 'International Journal of Numerical Methods in Fluids'),
  (85, 'volume', '56'),
  (85, 'year', '2008'),
  (85, 'pages', '1033-1046'),
  (86, 'author', 'A. Apte and C.K.R.T. Jones and A.M. Stuart'),
  (86, 'title', 'A Bayesian approach to Lagrangian data assimilation'),
  (86, 'journal', 'Tellus A'),
  (86, 'volume', '60'),
  (86, 'year', '2008'),
  (86, 'pages', '336-347'),
  (87, 'author', 'G. Pavliotis and A.M. Stuart and K. Zygalakis'),
  (87, 'title', 'Homogenization for inertial particles in a random flow'),
  (87, 'journal', 'Communications in Mathematical Sciences'),
  (87, 'volume', '5'),
  (87, 'year', '2007'),
  (87, 'pages', '507-531'),
  (88, 'author', 'M. Hairer and A.M. Stuart and J. Voss'),
  (88, 'title', 'Analysis of SPDEs arising in path sampling part II: the nonlinear case'),
  (88, 'journal', 'Annals of Applied Probability'),
  (88, 'volume', '17'),
  (88, 'issue', '5-6'),
  (88, 'year', '2007'),
  (88, 'pages', '1657-1706'),
  (89, 'author', 'G. Pavliotis and A.M. Stuart'),
  (89, 'title', 'Parameter estimation for multiscale diffusions'),
  (89, 'journal', 'Journal of Statistical Physics'),
  (89, 'volume', '127'),
  (89, 'year', '2007'),
  (89, 'pages', '741-781'),
  (90, 'author', 'A. Apte and M. Hairer and A.M. Stuart and J. Voss'),
  (90, 'title', 'A Bayesian approach to data assimilation'),
  (90, 'journal', 'Physica D Nonlinear Phenomena'),
  (90, 'volume', '230'),
  (90, 'year', '2007'),
  (90, 'pages', '50-64'),
  (91, 'author', 'H. Lamba and J.C. Mattingly and A.M. Stuart'),
  (91, 'title', 'An adaptive Euler-Maruyama scheme for SDEs: convergence and stability'),
  (91, 'journal', 'IMA Journal of Numerical Analysis'),
  (91, 'volume', '27'),
  (91, 'year', '2007'),
  (91, 'pages', '479-506'),
  (92, 'author', 'D. Barkley and I.G. Kevrekidis and A.M. Stuart'),
  (92, 'title', 'The moment map: nonlinear dynamics of density evolution via a few moments'),
  (92, 'journal', 'SIAM Journal of Applied Dynamical Systems'),
  (92, 'volume', '5'),
  (92, 'year', '2006'),
  (92, 'pages', '403-434'),
  (93, 'author', 'M. Hairer and A.M. Stuart and J. Voss and P. Wiberg'),
  (93, 'title', 'Analysis of SPDEs arising in path sampling part I: the Gaussian case'),
  (93, 'journal', 'Communications in Mathematical Sciences'),
  (93, 'volume', '4'),
  (93, 'year', '2005'),
  (93, 'pages', '587-603'),
  (94, 'author', 'G.A. Pavliotis and A.M. Stuart'),
  (94, 'title', 'Periodic homogenization for inertial particles'),
  (94, 'journal', 'Physica D Nonlinear Phenomena'),
  (94, 'volume', '204'),
  (94, 'year', '2005'),
  (94, 'pages', '161-187'),
  (95, 'author', 'G. Pavliotis and A.M. Stuart'),
  (95, 'title', 'Analysis of white noise limits for stochastic systems with two fast relaxation times'),
  (95, 'journal', 'SIAM Multiscale Modelling and Simulation'),
  (95, 'volume', '4'),
  (95, 'year', '2005'),
  (95, 'pages', '1-35'),
  (96, 'author', 'R. Kupferman and A.M. Stuart'),
  (96, 'title', 'Fitting SDE models to nonlinear Kac-Zwanzig heat bath models'),
  (96, 'journal', 'Physica D Nonlinear Phenomena'),
  (96, 'volume', '199'),
  (96, 'year', '2004'),
  (96, 'pages', '279-316'),
  (97, 'author', 'A.M. Stuart and P. Wiberg and J. Voss'),
  (97, 'title', 'Conditional path sampling of SDEs and the Langevin MCMC method'),
  (97, 'journal', 'Communications in Mathematical Sciences'),
  (97, 'volume', '2'),
  (97, 'issue', '4'),
  (97, 'year', '2004'),
  (97, 'pages', '685-697'),
  (98, 'author', 'R. Kupferman and G. Pavliotis and A.M. Stuart'),
  (98, 'title', 'Ito versus Stratonovich white noise limits for systems with inertia and colored multiplicative noise'),
  (98, 'journal', 'Physical Review E'),
  (98, 'volume', '70'),
  (98, 'year', '2004'),
  (98, 'pages', '036120'),
  (99, 'author', 'D. Givon and R. Kupferman and A.M. Stuart'),
  (99, 'title', 'Extracting macroscopic dynamics: model problems and algorithms'),
  (99, 'journal', 'Nonlinearity'),
  (99, 'volume', '17'),
  (99, 'year', '2004'),
  (99, 'pages', '55-127'),
  (100, 'author', 'D.J. Higham and X. Mao and A.M. Stuart'),
  (100, 'title', 'Mean square stability of numerical solutions to stochastic differential equations'),
  (100, 'journal', 'LMS Journal of Computational Mathematics'),
  (100, 'volume', '6'),
  (100, 'year', '2003'),
  (100, 'pages', '297-313'),
  (101, 'author', 'G. Pavliotis and A.M. Stuart'),
  (101, 'title', 'White noise limits for inertial particles in a random field'),
  (101, 'journal', 'SIAM Multiscale Modelling and Simulation'),
  (101, 'volume', '1'),
  (101, 'year', '2003'),
  (101, 'pages', '527-553'),
  (102, 'author', 'W. Husinga and C. Schutte and A.M. Stuart'),
  (102, 'title', 'Extracting macroscopic stochastic models from dynamics'),
  (102, 'journal', 'Communications in Pure and Applied Mathematics'),
  (102, 'volume', 'LVI'),
  (102, 'year', '2003'),
  (102, 'pages', '234-269'),
  (103, 'author', 'H. Sigurgeirsson and A.M. Stuart'),
  (103, 'title', 'A model for preferential concentration'),
  (103, 'journal', 'Physics of Fluids'),
  (103, 'volume', '14'),
  (103, 'year', '2002'),
  (103, 'pages', '4352-4361'),
  (104, 'author', 'H. Sigurgeirsson and A.M. Stuart'),
  (104, 'title', 'Inertial particles in a random field'),
  (104, 'journal', 'Stochastics and Dynamics'),
  (104, 'volume', '2'),
  (104, 'year', '2002'),
  (104, 'pages', '295-310'),
  (105, 'author', 'R. Kupferman and A.M. Stuart and J. Terry and P. Tupper'),
  (105, 'title', 'Long time behaviour of large mechanical systems with random initial data'),
  (105, 'journal', 'Stochastics and Dynamics'),
  (105, 'volume', '2'),
  (105, 'year', '2002'),
  (105, 'pages', '533-562'),
  (106, 'author', 'J. Mattingly and A.M. Stuart'),
  (106, 'title', 'Geometric ergodicity of some hypo-elliptic diffusions for particle motions'),
  (106, 'journal', 'Markov Processes and Related Fields'),
  (106, 'volume', '8'),
  (106, 'year', '2002'),
  (106, 'pages', '199-214'),
  (107, 'author', 'D.J. Higham and X. Mao and A.M. Stuart'),
  (107, 'title', 'Strong convergence of Euler type methods for nonlinear stochastic differential equations'),
  (107, 'journal', 'SIAM Journal of Numerical Analysis'),
  (107, 'volume', '40'),
  (107, 'issue', '3'),
  (107, 'year', '2002'),
  (107, 'pages', '1041-1063'),
  (107, 'doi', '10.1137/S0036142901389530'),
  (108, 'author', 'J. Mattingly and A.M. Stuart and D.J. Higham'),
  (108, 'title', 'Ergodicity for SDEs and approximations: locally Lipschitz vector fields and degenerate noise'),
  (108, 'journal', 'Stochastic Processes and their Applications'),
  (108, 'volume', '101'),
  (108, 'issue', '2'),
  (108, 'year', '2002'),
  (108, 'pages', '185-232'),
  (108, 'doi', '10.1016/S0304-4149(02)00150-3'),
  (109, 'author', 'D.J. Estep and A.M. Stuart'),
  (109, 'title', 'The dynamical behaviour of the discontinuous Galerkin method and related difference schemes'),
  (109, 'journal', 'Mathematics of Computation'),
  (109, 'volume', '71'),
  (109, 'year', '2002'),
  (109, 'pages', '1075-1103'),
  (110, 'author', 'H. Sigurgeirsson and A.M. Stuart and J. Wan'),
  (110, 'title', 'Collision detection for particles in a flow'),
  (110, 'journal', 'J. Comp. Phys.'),
  (110, 'volume', '172'),
  (110, 'year', '2001'),
  (110, 'pages', '766-807'),
  (111, 'author', 'B. Cano and A.M. Stuart'),
  (111, 'title', 'Under-resolved simulations of heat baths'),
  (111, 'journal', 'J. Comp. Phys.'),
  (111, 'volume', '169'),
  (111, 'year', '2001'),
  (111, 'pages', '193-214'),
  (112, 'author', 'B. Cano and E. Suli and A.M. Stuart and J. Warren'),
  (112, 'title', 'Stiff oscillatory systems, delta jumps and white noise'),
  (112, 'journal', 'Found. Comp. Math.'),
  (112, 'volume', '1'),
  (112, 'year', '2001'),
  (112, 'pages', '69-100'),
  (113, 'author', 'T. Shardlow and A.M. Stuart'),
  (113, 'title', 'A perturbation theory for ergodic Markov chains with application to numerical approximation'),
  (113, 'journal', 'SIAM J. Num. Anal.'),
  (113, 'volume', '37'),
  (113, 'year', '2000'),
  (113, 'pages', '1120-1137'),
  (114, 'author', 'A.M. Stuart and J. Warren'),
  (114, 'title', 'Analysis and experiments for a computational model of a heat bath'),
  (114, 'journal', 'J. Stat. Phys.'),
  (114, 'volume', '97'),
  (114, 'year', '1999'),
  (114, 'pages', '687-723'),
  (115, 'author', 'O. Gonzalez and D.J. Higham and A.M. Stuart'),
  (115, 'title', 'On the qualitative properties of modified equations'),
  (115, 'journal', 'IMA J. Num. Anal.'),
  (115, 'volume', '19'),
  (115, 'year', '1999'),
  (115, 'pages', '169-190'),
  (116, 'author', 'J.M. Sanz-Serna and A.M. Stuart'),
  (116, 'title', 'Ergodic Properties of Dissipative Differential Equations Subject to Random Impulses'),
  (116, 'journal', 'J. Diff. Eq.'),
  (116, 'volume', '155'),
  (116, 'year', '1999'),
  (116, 'pages', '262-284'),
  (117, 'author', 'H. Lamba and A.M. Stuart'),
  (117, 'title', 'Convergence Results for the MATLAB ode23 Routine'),
  (117, 'journal', 'BIT'),
  (117, 'volume', '38'),
  (117, 'year', '1998'),
  (117, 'pages', '751-780'),
  (118, 'author', 'D.A. Jones and A.M. Stuart and E.S. Titi'),
  (118, 'title', 'Persistence of Invariant Sets for Dissipative Evolution Equations'),
  (118, 'journal', 'J. Math. Anal. and Applies.'),
  (118, 'volume', '219'),
  (118, 'year', '1998'),
  (118, 'pages', '479-502'),
  (119, 'author', 'M. Gander and A.M. Stuart'),
  (119, 'title', 'Parallel Algorithms for the Solution of Time-Dependent Partial Differential Equations'),
  (119, 'journal', 'SIAM J. Sci. Comp.'),
  (119, 'volume', '19'),
  (119, 'year', '1998'),
  (119, 'pages', '2014-2031'),
  (120, 'author', 'C.J. Budd and G.P. Koomullil and A.M. Stuart'),
  (120, 'title', 'On the solution of convection-diffusion boundary-value problems by grid adaptation'),
  (120, 'journal', 'SIAM J. Sci. Stat. Comp.'),
  (120, 'volume', '20'),
  (120, 'year', '1998'),
  (120, 'pages', '591-618'),
  (121, 'author', 'D.J. Higham and A.M. Stuart'),
  (121, 'title', 'Analysis of the dynamics of error control via a piecewise continuous residual'),
  (121, 'journal', 'BIT'),
  (121, 'volume', '38'),
  (121, 'year', '1998'),
  (121, 'pages', '44-57'),
  (122, 'author', 'A.M. Stuart'),
  (122, 'title', 'Probabilistic and Deterministic Convergence Proofs for Software for Ini­tial Value Problems'),
  (122, 'journal', 'Numerical Algorithms'),
  (122, 'volume', '14'),
  (122, 'year', '1997'),
  (122, 'pages', '227-260'),
  (123, 'author', 'M. Bjorhus and A.M. Stuart'),
  (123, 'title', 'Waveform relaxation as a dynamical system'),
  (123, 'journal', 'Math. Comp.'),
  (123, 'volume', '66'),
  (123, 'year', '1997'),
  (123, 'pages', '1101-1117'),
  (124, 'author', 'C.M. Elliott and A.M. Stuart'),
  (124, 'title', 'The viscous Cahn-Hilliard equation. Part II: Analysis'),
  (124, 'journal', 'J. Diff. Equations'),
  (124, 'volume', '128'),
  (124, 'year', '1996'),
  (124, 'pages', '387-414'),
  (125, 'author', 'D.A. Jones and A.M. Stuart'),
  (125, 'title', 'Attractive Invariant Manifolds Under Approximation. Part I: Inertial Manifolds'),
  (125, 'journal', 'J. Diff. Eq.'),
  (125, 'volume', '123'),
  (125, 'year', '1995'),
  (125, 'pages', '588-637'),
  (126, 'author', 'A.M. Stuart and A.R. Humphries'),
  (126, 'title', 'The Essential Stability of Local Error Control for Dissipative and Gradient Dynamical Systems'),
  (126, 'journal', 'SIAM J. Num. Anal.'),
  (126, 'volume', '32'),
  (126, 'year', '1995'),
  (126, 'pages', '1940-1971'),
  (127, 'author', 'G.J. Lord and A.M. Stuart'),
  (127, 'title', 'Gevrey regularity and upper semicontinuity of attractors for a semi-discrete Ginzburg-Landau equation'),
  (127, 'journal', 'Num. Func. Anal. Appl.'),
  (127, 'volume', '16'),
  (127, 'year', '1995'),
  (127, 'pages', '1003-1047'),
  (128, 'author', 'D.J. Estep and A.M. Stuart'),
  (128, 'title', 'The rate of error growth in Hamiltonian conserving integrators'),
  (128, 'journal', 'ZAMP'),
  (128, 'volume', '46'),
  (128, 'year', '1995'),
  (128, 'pages', '407-418'),
  (129, 'author', 'F. Bai and C.M. Elliott and A. Gardiner and A. Spence and A.M. Stuart'),
  (129, 'title', 'The viscous Cahn- Hilliard equation. Part I: Computations'),
  (129, 'journal', 'Nonlinearity'),
  (129, 'volume', '8'),
  (129, 'year', '1995'),
  (129, 'pages', '131-160'),
  (130, 'author', 'F. Bai and A. Spence and A.M. Stuart'),
  (130, 'title', 'Numerical Computations of Coarsening in the Cahn-Hilliard model of phase separation'),
  (130, 'journal', 'Physica D'),
  (130, 'volume', '78'),
  (130, 'year', '1994'),
  (130, 'pages', '155-165'),
  (131, 'author', 'A.M. Stuart and A.R. Humphries'),
  (131, 'title', 'Model Problems in Numerical Stability for Initial Value Problems'),
  (131, 'journal', 'SIAM Review'),
  (131, 'volume', '36'),
  (131, 'year', '1994'),
  (131, 'pages', '226-257'),
  (132, 'author', 'A.R. Humphries and A.M. Stuart'),
  (132, 'title', 'Runge-Kutta methods for disspative and gradient dynamical systems'),
  (132, 'journal', 'SIAM J. Num. Anal.'),
  (132, 'volume', '31'),
  (132, 'year', '1994'),
  (132, 'pages', '1452-1485'),
  (133, 'author', 'C.J. Budd and J.W. Dold and A.M. Stuart'),
  (133, 'title', 'The study of blow-up in a system of partial differential equations with conserved first integral. Part II: Non-zero convection'),
  (133, 'journal', 'SIAM J. Appl. Math.'),
  (133, 'volume', '54'),
  (133, 'year', '1994'),
  (133, 'pages', '610-640'),
  (134, 'author', 'F. Bai and A. Spence and A.M. Stuart'),
  (134, 'title', 'The Numerical Computation of Heteroclinic Connections in Systems of Gradient Partial Differential Equations'),
  (134, 'journal', 'SIAM J. Appl. Math.'),
  (134, 'volume', '35'),
  (134, 'year', '1993'),
  (134, 'pages', '743-769'),
  (135, 'author', 'C.J. Budd and J.W. Dold and A.M. Stuart'),
  (135, 'title', 'The study of blow-up in a system of partial differential equations with conserved first integral. Part I: Zero convection'),
  (135, 'journal', 'SIAM J. Appl. Math.'),
  (135, 'volume', '53'),
  (135, 'year', '1993'),
  (135, 'pages', '718-742'),
  (136, 'author', 'C.M. Elliott and A.M. Stuart'),
  (136, 'title', 'The global dynamics of discrete semilinear parabolic equations'),
  (136, 'journal', 'SIAM J. Num. Anal.'),
  (136, 'volume', '30'),
  (136, 'year', '1993'),
  (136, 'pages', '1622-1663'),
  (137, 'author', 'M.A.J. Chaplain and A.M. Stuart'),
  (137, 'title', 'A model mechanism for the chemotactic response of endothelial cells to tumour angiogenesis factor'),
  (137, 'journal', 'IMA J. Math. Appl. Med. Biol.'),
  (137, 'volume', '10'),
  (137, 'year', '1993'),
  (137, 'pages', '149-168'),
  (138, 'author', 'J.M. Sanz-Serna and A.M. Stuart'),
  (138, 'title', 'A note on uniform in time error estimates for reaction-diffusion equations'),
  (138, 'journal', 'IMA J. Num. Anal.'),
  (138, 'volume', '12'),
  (138, 'year', '1992'),
  (138, 'pages', '457-46'),
  (139, 'author', 'D.F. Griffiths and A.M. Stuart and H.C. Yee'),
  (139, 'title', 'Numerical wave propagation in hyperbolic equations with source terms'),
  (139, 'journal', 'SIAM J. Num. Anal.'),
  (139, 'volume', '29'),
  (139, 'year', '1992'),
  (139, 'pages', '1244-1260'),
  (140, 'author', 'A. Iserles and A.M. Stuart'),
  (140, 'title', 'A unified approach to spurious solutions introduced by time discretisation. Part II. BDF-like methods'),
  (140, 'journal', 'IMA J. Num. Anal.'),
  (140, 'volume', '12'),
  (140, 'year', '1992'),
  (140, 'pages', '487-502'),
  (141, 'author', 'M.A.J. Chaplain and A.M. Stuart'),
  (141, 'title', 'A mathematical model for the diffusion of tumour angiogenesis factor into the surrounding host tissue'),
  (141, 'journal', 'IMA J. Math. Appl. Med. Biol.'),
  (141, 'volume', '8'),
  (141, 'year', '1991'),
  (141, 'pages', '191-220'),
  (142, 'author', 'A. Iserles and A.T. Peplow and A.M. Stuart'),
  (142, 'title', 'A unified approach to spurious solutions introduced by time-discretisation. Part I Basic Theory'),
  (142, 'journal', 'SIAM J. Num. Anal.'),
  (142, 'volume', '28'),
  (142, 'year', '1991'),
  (142, 'pages', '1723-1751'),
  (143, 'author', 'A.M. Stuart and A.T. Peplow'),
  (143, 'title', 'The dynamics of the theta method'),
  (143, 'journal', 'SIAM J. Sci. Stat. Comp.'),
  (143, 'volume', '12'),
  (143, 'year', '1991'),
  (143, 'pages', '1351-1372'),
  (144, 'author', 'A.M. Stuart'),
  (144, 'title', 'Singular Limits In Free Boundary Problems'),
  (144, 'journal', 'Rocky Mountain J. Math.'),
  (144, 'volume', '21'),
  (144, 'year', '1991'),
  (144, 'pages', '809-811'),
  (145, 'author', 'A.M. Stuart and M.S. Floater'),
  (145, 'title', 'On the Computation of Blow-up'),
  (145, 'journal', 'Euro. J. Appl. Math.'),
  (145, 'volume', '1'),
  (145, 'year', '1990'),
  (145, 'pages', '47-71'),
  (146, 'author', 'A.M. Stuart'),
  (146, 'title', 'Linear Instability Implies Spurious Periodic Solutions'),
  (146, 'journal', 'IMA J. Num. Anal.'),
  (146, 'volume', '9'),
  (146, 'year', '1989'),
  (146, 'pages', '465-486'),
  (147, 'author', 'J. Norbury and A.M. Stuart'),
  (147, 'title', 'A Model For Porous Medium Combustion'),
  (147, 'journal', 'Quart. J. Mech. Appl. Math.'),
  (147, 'volume', '42'),
  (147, 'year', '1989'),
  (147, 'pages', '159-178'),
  (148, 'author', 'A.M. Stuart'),
  (148, 'title', 'A Note On High/Low Wave Number Interactions In Spatially Discrete Parabolic Equations'),
  (148, 'journal', 'IMA J. Appl. Math.'),
  (148, 'volume', '42'),
  (148, 'year', '1989'),
  (148, 'pages', '27-42'),
  (149, 'author', 'A.M. Stuart'),
  (149, 'title', 'Nonlinear Instability In Dissipative Finite Difference Schemes'),
  (149, 'journal', 'SIAM Review'),
  (149, 'volume', '31'),
  (149, 'year', '1989'),
  (149, 'pages', '191-220'),
  (150, 'author', 'A.M. Stuart'),
  (150, 'title', 'Singular Free Boundary Problems And Local Bifurcation Theory'),
  (150, 'journal', 'SIAM J. Appl. Math.'),
  (150, 'volume', '49'),
  (150, 'year', '1989'),
  (150, 'pages', '72-85'),
  (151, 'author', 'A.M. Stuart'),
  (151, 'title', 'Similarity Solutions of a Heat Equation with Nonlinearly Varying Heat Capacity'),
  (151, 'journal', 'IMA J. Appl. Math.'),
  (151, 'volume', '40'),
  (151, 'year', '1988'),
  (151, 'pages', '217-234'),
  (152, 'author', 'J. Norbury and A.M. Stuart'),
  (152, 'title', 'Parabolic Free Boundary Problems Arising in Porous Medium Combustion'),
  (152, 'journal', 'IMA J. Appl. Math.'),
  (152, 'volume', '39'),
  (152, 'year', '1988'),
  (152, 'pages', '241-257'),
  (153, 'author', 'J. Norbury and A.M. Stuart'),
  (153, 'title', 'Travelling Combustion Waves in a Porous Medium. Part II - Stability'),
  (153, 'journal', 'SIAM J. Appl. Math.'),
  (153, 'volume', ''),
  (153, 'year', '1988'),
  (153, 'pages', '374-392'),
  (154, 'author', 'J. Norbury and A.M. Stuart'),
  (154, 'title', 'Travelling Combustion Waves in a Porous Medium. Part I - Existence'),
  (154, 'journal', 'SIAM J. Appl. Math.'),
  (154, 'volume', '48'),
  (154, 'year', '1988'),
  (154, 'pages', '155-169'),
  (155, 'author', 'A.M. Stuart'),
  (155, 'title', 'Existence of Solutions of a Two-Point Free Boundary Problem Arising in the Theory of Porous Medium Combustion'),
  (155, 'journal', 'IMA J. Appl. Math.'),
  (155, 'volume', '38'),
  (155, 'year', '1987'),
  (155, 'pages', '23-34'),
  (156, 'author', 'J. Norbury and A.M. Stuart'),
  (156, 'title', 'Volterra Integral Equations and a New Gronwall Inequality. Part II: The Nonlinear Case'),
  (156, 'journal', 'Proc. Roy. Soc. Edin.'),
  (156, 'volume', '106A'),
  (156, 'year', '1987'),
  (156, 'pages', '375-384'),
  (157, 'author', 'J. Norbury and A.M. Stuart'),
  (157, 'title', 'Volterra Integral Equations and a New Gronwall Inequality. Part I: The Linear Case'),
  (157, 'journal', 'Proc. Roy. Soc. Edin.'),
  (157, 'volume', '106A'),
  (157, 'year', '1987'),
  (157, 'pages', '361-373'),
  (158, 'author', 'A.M. Stuart and A.Taeb'),
  (158, 'title', 'Inverse Problems and Data Assimilation'),
  (158, 'note', 'In preparation'),
  (160, 'author', 'K.J.H.Law and A.M.Stuart and K.C.Zygalakis'),
  (160, 'title', 'Data Assimilation: A Mathematical Introduction'),
  (160, 'publisher', 'Springer'),
  (160, 'year', '2015'),
  (161, 'author', 'G.A. Pavliotis and A.M. Stuart'),
  (161, 'title', 'Multiscale Methods: Averaging and Homogenization'),
  (161, 'publisher', 'Springer'),
  (161, 'year', '2008'),
  (162, 'author', 'O. Gonzalez and A.M. Stuart'),
  (162, 'title', 'A First Course in Continuum Mechanics'),
  (162, 'publisher', 'Cambridge University Press'),
  (162, 'year', '2008'),
  (163, 'author', 'A.M. Stuart and A.R. Humphries'),
  (163, 'title', 'Dynamical Systems and Numerical Analysis'),
  (163, 'publisher', 'Cambridge University Press'),
  (163, 'year', '1996'),
  (164, 'author', 'P.Buhlmann and A.M. Stuart'),
  (164, 'title', 'Mathematics, Statistics and Data Science'),
  (164, 'booktitle', 'EMS Newsletter'),
  (164, 'volume', 'June 2016'),
  (164, 'publisher', 'EMS'),
  (164, 'pages', '28-30'),
  (165, 'author', 'S.Reich and A.M. Stuart'),
  (165, 'title', 'Data Assimilation: New Challenges in Random and Stochastic Dynamical Systems'),
  (165, 'booktitle', 'SIAM News'),
  (165, 'volume', 'October and November 2015'),
  (165, 'publisher', 'SIAM'),
  (166, 'author', 'M. Dashti and A.M.Stuart'),
  (166, 'title', 'The Bayesian Approach to Inverse Problems'),
  (166, 'booktitle', 'Handbook of Uncertainty Quantification'),
  (166, 'editor', 'R. Ghanem and D. Higdon and H. Owhadi'),
  (166, 'publisher', 'Springer'),
  (167, 'author', 'M. Iglesias and A.M. Stuart'),
  (167, 'title', 'Inverse Problems and Uncerrainty Quantification'),
  (167, 'booktitle', 'SIAM News'),
  (167, 'volume', 'July/August 2014'),
  (167, 'publisher', 'SIAM'),
  (168, 'author', 'G. Pavliotis and Y. Pokern and A.M. Stuart'),
  (168, 'title', 'Parameter estimation for multiscale diffusions: an overview'),
  (168, 'booktitle', 'Statistical Methods for Stochastic Differential Equations'),
  (168, 'volume', '7'),
  (168, 'publisher', 'CRC Press'),
  (168, 'editor', 'M. Kessler and A. Lindner and M. Sorensen'),
  (168, 'arXiv', 'arXiv:math/0603668'),
  (169, 'author', 'J. Nolen and G. Pavliotis and A.M. Stuart'),
  (169, 'title', 'Multiscale modelling and inverse problems'),
  (169, 'booktitle', 'Lecture Notes in Computational Science and Engineering'),
  (169, 'volume', '83'),
  (169, 'publisher', 'Springer'),
  (169, 'editor', 'I.G. Graham and Th. Y. Hou and O. Lakkis and R. Scheichl'),
  (170, 'author', 'M. Hairer and A.M. Stuart and J. Voss'),
  (170, 'title', 'Signal processing problems on function space: Bayesian formulation, stochastic PDEs and effective MCMC methods'),
  (170, 'booktitle', 'The Oxford Handbook of Nonlinear Filtering'),
  (170, 'publisher', 'Oxford University Press'),
  (170, 'editor', 'D. Crisan and B. Rozovsky'),
  (170, 'pages', '833-873'),
  (171, 'author', 'A.M. Stuart'),
  (171, 'title', 'Inverse problems: a Bayesian perspective'),
  (171, 'booktitle', 'Acta Numerica 2010'),
  (171, 'volume', '19'),
  (171, 'pages', '451--559'),
  (172, 'author', 'D. White and A.M. Stuart'),
  (172, 'title', 'Greens Functions by Monte Carlo'),
  (172, 'booktitle', 'Monte Carlo and Quasi-Monte Carlo Methods 2008'),
  (172, 'publisher', 'Springer'),
  (172, 'editor', 'P. L''Ecuyer and A.B. Owen'),
  (172, 'year', '2009'),
  (173, 'author', 'A. Beskos and A.M. Stuart'),
  (173, 'title', 'Computational Complexity of Metropolis-Hastings Methods in High Dimensions'),
  (173, 'booktitle', 'Monte Carlo and Quasi-Monte Carlo Methods 2008'),
  (173, 'publisher', 'Springer'),
  (173, 'editor', 'P. L''Ecuyer and A.B. Owen'),
  (173, 'year', '2009'),
  (174, 'author', 'A. Beskos and A.M. Stuart'),
  (174, 'title', 'MCMC methods for sampling function space'),
  (174, 'booktitle', 'ICIAM Invited Lecture 2007'),
  (174, 'publisher', 'European Mathematical Society'),
  (174, 'editor', 'R. Jeltsch and G. Wanner'),
  (174, 'year', '2008'),
  (175, 'author', 'M. Hairer and A.M. Stuart and J. Voss'),
  (175, 'title', 'Sampling conditioned diffusions'),
  (175, 'booktitle', 'Trends in Stochastic Analysis'),
  (175, 'publisher', 'Cambridge University Press'),
  (175, 'series', 'LMS Lecture Notes 353'),
  (175, 'editor', 'J. Blath and P. Mörters and M. Sceutzow'),
  (175, 'year', '2008'),
  (176, 'author', 'G.A. Pavliotis and A.M. Stuart and L. Band'),
  (176, 'title', 'Monte Carlo studies of effective diffusivities for inertial particles'),
  (176, 'booktitle', 'Monte Carlo and Quasi-Monte Carlo Methods 2004'),
  (176, 'publisher', 'Springer Verlag'),
  (176, 'pages', '431-441'),
  (176, 'editor', 'H. Niederreiter and D. Talay'),
  (176, 'year', '2006'),
  (177, 'author', 'A.R. Humphries and A.M. Stuart'),
  (177, 'title', 'Numerical Analysis of Deterministic and Random Dynamical Systems'),
  (177, 'booktitle', 'Modern Methods in Scientific Computing and Applications'),
  (177, 'publisher', 'Kluwer'),
  (177, 'series', 'NATO Science Series II'),
  (177, 'editor', 'A. Bourlioux and M.J. Gander'),
  (177, 'year', '2001'),
  (178, 'author', 'H. Sigurgeirsson and A.M. Stuart'),
  (178, 'title', 'Statistics from computations'),
  (178, 'booktitle', 'Foundations of Computational Mathematics'),
  (178, 'series', 'LMS Lecture Note Series'),
  (178, 'publisher', 'LMS'),
  (178, 'editor', 'R.A. DeVore and A. Iserles and E. Suli'),
  (178, 'year', '2001'),
  (179, 'author', 'H. Lamba and A.M. Stuart'),
  (179, 'title', 'Convergence proofs for numerical software'),
  (179, 'booktitle', 'Dynamics of Algorithms'),
  (179, 'series', 'IMA Volumes in Mathematics and its Applications'),
  (179, 'publisher', 'Springer'),
  (179, 'editor', 'R. de la Llave and L. Petzold and J. Lorenz'),
  (179, 'year', '1999'),
  (180, 'author', 'A.M. Stuart'),
  (180, 'title', 'Convergence and stability in the numerical approximation of dynamical systems'),
  (180, 'booktitle', 'Start of the Art in Numerical Analysis 1996'),
  (180, 'publisher', 'Oxford University Press'),
  (180, 'editor', 'I.A. Duff and G.A Watson'),
  (180, 'year', '1996'),
  (181, 'author', 'A.M. Stuart'),
  (181, 'title', 'Perturbation Theory for Infinite Dimensional Dynamical Systems'),
  (181, 'booktitle', 'Advances in Numerical Analysis'),
  (181, 'publisher', 'Oxford University Press'),
  (181, 'pages', '105'),
  (181, 'editor', 'M. Ainsworth and J. Levesley and M. Marletta and W.A. Light'),
  (181, 'year', '1995');
